### ISSUE TITLE
Lockless concurrency

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#10]
In GitLab by @pzakopaylo01 on Jan 18, 2018, 20:06

We need to port some lockless concurrency-based implementations to Rust, e.g. spinlocks for forwarding words in copying collectors and the synchronized counter when scanning threads.

This is hard because we need to understand the Java memory model and translate it to LLVM/C/Rust memory ordering.

**Comment by wks** [comment]
The atomic types, such as `AtomicUsize`, `AtomicU64`, `AtomicI64`, `AtomicU32`, ..., have been stabilized since Rust 1.34.0.  As for 1.72.0, they currently follow the memory model of C++20 atomics, and their mapping to the Java memory model is clear (Relaxed = opaque/plain, SeqCst = volatile).  Now we actively use those atomic types (and the `Atomic<T>` wrapper from the `atomic` crate) in Rust MMTk.  We can close this issue now.
