### ISSUE TITLE
Pages are mapped without checking the budget when collection is not enabled

### ISSUE THREAD

**Issue by wangbrenda** [mmtk/mmtk-core#214]
https://github.com/mmtk/mmtk-core/blob/bb9fd6c/src/policy/space.rs#L237

When a space acquires pages, it only `poll`s if `allow_poll` is true. `allow_poll` can only be true if the plan is initialized, where the flag is set by https://github.com/mmtk/mmtk-core/blob/4e09cfb2078add72ed81c45779609d376a667fe2/src/mm/memory_manager.rs#L176

Considering the following scenario. If a VM port only uses `NoGC`, they might only call `gc_init` but not `enable_collection`.
So even if the heap size is 0, the acquire of pages will still succeed.

So we should either make sure `acquire` behave as expected (i.e. reporting OOM if the heap size is 0 even if collection is not enabled) or be explicit about what `enable_collection` does.

cc @caizixian

**Comment by qinsoon** [comment]
Thanks for submitting the issue. 

Can we modify this line to only check `is_mutator && poll()` which will properly check heap size? If it fails (which means we want to trigger a GC), we do a check to see if mmtk is `initialized` - it panics if not initialized because we cannot do a GC without calling `enable_collection()`.
https://github.com/mmtk/mmtk-core/blob/bb9fd6c9acfd685af729ca6be9a9d3cb9b26435f/src/policy/space.rs#L246

If this works, it should be a small PR and I can do it tomorrow. As for 0 or negative heap size, we can have a check in `gc_init()` to make sure heap size is valid.
