### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by caizixian** [mmtk/mmtk-core#289]
- [ ] #206 Add support for aarch64
- [ ] Port each of the bindings to ARM

**Comment by caizixian** [comment]
@k-sareen did some initial work on porting the OpenJDK binding to aarch64

**Comment by KipHamiltons** [comment]
I just inadvertently started porting the openjdk binding to apple silicon inside a docker container, but I got stuck on some inline assembly in `$mmtk-openjdk/openjdk/barriers/mmtkObjectBarrier.cpp` which I am not confident to convert. I'll note what I did to get to that point, although I understand most of it is really more relevant to the openjdk binding repo.

First, `gcc-multilib` isn't a package I could get off apt-get. Perhaps because apple banished 32 bit code a while back? I removed it from the package list and continued.
Openjdk's configure script required these extra packages, so I got them with apt:   `x11proto-randr-dev libxrandr-dev x11proto-randr-dev`
I replaced the `CONF` variable in the `make` call for openjdk with `CONF=linux-aarch64-normal-server-$DEBUG_LEVEL`.
I added a declaration for a C function in the openjdk source:
```diff
diff --git a/src/hotspot/cpu/aarch64/icache_aarch64.hpp b/src/hotspot/cpu/aarch64/icache_aarch64.hpp
index 30c7a408a8d..fa261d64020 100644
--- a/src/hotspot/cpu/aarch64/icache_aarch64.hpp
+++ b/src/hotspot/cpu/aarch64/icache_aarch64.hpp
@@ -30,6 +30,10 @@
 // modifies code, part of the processor instruction cache potentially
 // has to be flushed.
 
+extern "C" {
+    void __clear_cache (char *beg, char *end);
+}
+
 class ICache : public AbstractICache {
  public:
   static void initialize();
```

Then I guessed a `MAX_ALIGNMENT_SHIFT` in `mmtk-core/src/vm/mod.rs` for `aarch64`:
```diff
diff --git a/src/vm/mod.rs b/src/vm/mod.rs
index 10b678ec..010bf07f 100644
--- a/src/vm/mod.rs
+++ b/src/vm/mod.rs
@@ -53,6 +53,10 @@ where
     /// Allowed maximum alignment as shift by min alignment.    
     const MAX_ALIGNMENT_SHIFT: usize = LOG_BYTES_IN_LONG as usize - LOG_BYTES_IN_INT as usize;
 
+    #[cfg(target_arch = "aarch64")]
+    /// TODO: Review this
+    const MAX_ALIGNMENT_SHIFT: usize = LOG_BYTES_IN_LONG as usize - LOG_BYTES_IN_INT as usize;
+
     /// Allowed maximum alignment in bytes.
     const MAX_ALIGNMENT: usize = Self::MIN_ALIGNMENT << Self::MAX_ALIGNMENT_SHIFT;
 ```

and that's where it failed because of the inline asm in the binding. The hardest parts are probably to come with the asm conversion, but I figure this is a start 😅

**Comment by CeleritasCelery** [comment]
I just came across this project then found out is is currently Linux x86 only. I am using Aarch64 on MacOS. When attempting the build it is using 2 Linux only symbols: `malloc_usable_size` and `MAP_FIXED_NOREPLACE`. Are there any plans to move beyond Linux x86? What would be the hurdles there?


```rust
error[E0432]: unresolved import `libc::malloc_usable_size`
  --> src/util/malloc.rs:21:30
   |
21 | pub use libc::{calloc, free, malloc_usable_size, posix_memalign};
   |                              ^^^^^^^^^^^^^^^^^^ no `malloc_usable_size` in the root

error[E0425]: cannot find value `MAP_FIXED_NOREPLACE` in crate `libc`
  --> src/util/memory.rs:48:60
   |
48 |     let flags = libc::MAP_ANON | libc::MAP_PRIVATE | libc::MAP_FIXED_NOREPLACE;
   |                                                            ^^^^^^^^^^^^^^^^^^^ not found in `libc`
```

**Comment by k-sareen** [comment]
Theoretically, there shouldn't be any big hurdles for the core. I think for core, the main thing we need to be careful about would be working around `MAP_FIXED_NOREPLACE` for MacOS. However, the actual major work needed to be done would be converting x86 assembly to the AArch64 equivalent in our bindings (some bindings such as OpenJDK essentially ues inline x86 assembly for JIT compilation).

Yes, we definitely want to support different architectures as well as operating systems, though I'm not sure what our timeline for those are (we're currently prepping for a v1.0 release), sorry.

**Comment by CeleritasCelery** [comment]
Thanks for the reply. I am excited you are working towards a 1.0 release! Would you be open to PR’s to improve support on different systems in core?

**Comment by k-sareen** [comment]
Absolutely! Thank you for considering contributing! I would recommend checking out [our contribution guidelines](https://github.com/mmtk/mmtk-core/blob/master/CONTRIBUTING.md) and joining [our Zulip](https://mmtk.zulipchat.com/) to discuss your proposals with our team.

**Comment by caizixian** [comment]
The core doesn't have any problem on aarch64 anymore, and the OpenJDK binding now works on aarch64.

**Comment by caizixian** [comment]
If other bindings need architectural ports, then we should create issues in the binding repo.
