### ISSUE TITLE
ImmixAllocator should use BumpAllocator fastpath

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#557]
`ImmixAllocator` uses the same fast path allocation as `BumpAllocator`. Also a VM's compiler can generate immix fastpath in the same way as bump pointer allocator (except that the field offsets may be different). 

It is unclear how to achieve this in the code. One possible implementation is to embed a `BumpAllocator` in `ImmixAllocator`, and use it for the fastpath allocation. 

A JIT compiler would only need to know what allocator fastpath to generate. So maybe we can have a separate type for `AllocatorFastpath`?

**Comment by wks** [comment]
If a VM binding really cares about performance, it should make use of the `BumpPointer` data structure, and operate on the `cursor` and the `limit` directly in JIT-compiled code.  We also have the `AllocatorInfo` struct to help the VM binding locate the `BumpPointer` struct.  Therefore, the whether the allocator is `ImmixAllocator` or `BumpAllocator` does not affect the fast-path implementation because `AllocatorInfo` will return the location of `BumpPointer` for both allocators.  We consider this issue solved.
