### ISSUE TITLE
Provide a way to get the plan name at runtime

### ISSUE THREAD

**Issue by chrisseaton** [mmtk/mmtk-core#583]
Ruby has a way to print various configuration options (which JIT it's using etc.) We'd like to be able to print out which GC is being used, so the plan name. We think we'd like a method `get_name` on `Plan` for example, but we're not very experienced with the architecture of MMTk.

**Comment by qinsoon** [comment]
That should be possible with the current public API. Plan is an option:
https://github.com/mmtk/mmtk-core/blob/ce82a7d9a5a1b9e4f83e0b70137430d7686c296a/src/util/options.rs#L308-L309

You can store it as a string somewhere, and create a C function to get it.
```rust
lazy_static!{
    // Get the plan option from from the MMTk instance. Dereference it to get a PlanSelector.
    // Debug print it into a String, and then into a CString
    static ref MMTK_PLAN_STR: CString = CString::new(format!("{:?}", *SINGLETON.get_options().plan)).unwrap();
}

#[no_mangle]
pub extern "C" fn get_plan() -> *const c_char {
    MMTK_PLAN_STR.as_ptr()
}
```

**Comment by chrisseaton** [comment]
@wks could you please add a `extern char *mmtk_plan_name(void)` function that I can use from Ruby?

**Comment by wks** [comment]
@chrisseaton Instead of adding it to mmtk-core, I added a C API in the mmtk-ruby repository, because mmtk-core doesn't expose C API.  All public Rust functions are callable from the binding, and the binding can make wrappers in whatever language relevant for that VM.  The commit is: https://github.com/mmtk/mmtk-ruby/commit/7c08f3d851219767886288fc1a52ad773b86b329

I also added a method in the Ruby VM so that we can query the plan name in Ruby.  Please have a look and see if my code has any problems.  https://github.com/mmtk/ruby/pull/6
