### ISSUE TITLE
Allocation offset should be `usize`

### ISSUE THREAD

**Issue by qinsoon** [mmtk/mmtk-core#674]
We have the `offset` type as `isize`:
https://github.com/mmtk/mmtk-core/blob/f82848847a6392537fec6b914d7ad95fbf28b0a2/src/util/alloc/allocator.rs#L157

However, in here, we specifically require `offset` to be positive:
https://github.com/mmtk/mmtk-core/blob/f82848847a6392537fec6b914d7ad95fbf28b0a2/src/util/alloc/allocator.rs#L48

We should change the type of `offset` to `usize` instead.

**Comment by fepicture** [comment]
Hi, I am new to this repo and intend to do this one.
below is my understanding:
* replace all allocation offset to `usize` (those alloc wrappers all need to be changed)
* remove useless assert since we have move to positive `offset`

my question is do I need to add a unit test? alloc at a negative `offset` sounds a bit weird.

**Comment by fepicture** [comment]
> 

thanks for your quick reply!
actually, I am also new to Rustc(hahaha :) 
I have no other concerns and will start on this.
