### ISSUE TITLE
Properly clear VO bits for ImmixSpace

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-core#844]
The current code in ImmixSpace does not clear VO bits for dead objects in marked lines.  This is obviously incorrect.  One consequence is that dead objects may be identified as live objects during conservative root scanning.

Goal: We should make sure that after each GC, VO bits are set if and only if the address corresponds to a live object.

Possible solutions:

1.  Clear the entire VO bits metadata right after the `Prepare` stage.  This method is described in [this paper](https://users.cecs.anu.edu.au/~steveb/pubs/papers/consrc-oopsla-2014.pdf).  The problem is, VO bits will not be available during tracing.
    a.  Clear VO bits after `Prepare`, but we keep two instances of the VO bits metadata.  During GC, we use one instance to identify objects, but reconstruct the new VO bits metadata in the other copy.
    b.  Clear VO bits after `Prepare`, but we keep two bitmaps.  We use one bitmap as mark bits and the other as VO bits, but we swap their roles after each GC.
2.  During sweeping, we copy the mark bits of marked lines to the VO bits metadata.  Given that both VO bits and mark bits have the same granularity, and mark bits always uses `1` for "marked" in side metadata, this should always work.

We need the VO bits to be available during tracing if we want to
-   support interior pointers
-   validate references during tracing (for example, dumping the heap during tracing while being tolerant to invalid edges)

Option (1) should be the cheapest because it only involves bulk zeroing which is as cheap as clearing the mark bits.  But if we have any of the above requirements, we can't use (1), but (1a), (1b) and (2) are all applicable.

**Comment by steveblackburn** [comment]
We did not do option 2 in the original implementation because it will only work efficiently with side metadata mark bits, and in JikesRVM we had in-header mark bits.

For debugging applications, requiring that mark bits be on the side would be fine.   But in general, we don't assume that mark bits are on the side because (we believe) it is more efficient (in time and space) to put the bits in the header in the cases where the VM is cooperative about it.

**Comment by steveblackburn** [comment]
There are three use-cases (AFAIK):

1. Stack-conservative GC, as we previously implemented in MMTk.   We took approach 1 because it was efficient and sufficient.
2. Interior pointers.   We don't support them yet, but we want to.
3. Debugging.

High performance stack-conservative GC remains a high priority for MMTk, and our prior work showed how to implement that in the old MMTk.   Debugging is also a very high priority, but of course overheads associated with debugging should be only paid when they're needed.   Interior pointers remain a priority for MMTk, but not a critical one.  

For now, the approach should be for overheads only to be paid when the relevant semantics are needed.   So we should be following the original implementation or another one that is just as efficient, and when we need debugging, we can pay the additional penalty of duplicating the VOB map, and likewise for interior pointers.  I suspect that there may be other, less expensive solutions for interior pointers than those listed above, depending on how common interior heap pointers are, and we can investigate that further, when that becomes a priority.

**Comment by wks** [comment]
https://github.com/mmtk/mmtk-core/issues/848 was supposed to be a sub-issue for Immix and GenImmix but not StickyImmix.  But the PR https://github.com/mmtk/mmtk-core/pull/849 ended up fixing StickyImmix, too.  So this issue can be closed.

> We did not do option 2 in the original implementation because it will only work efficiently with side metadata mark bits, and in JikesRVM we had in-header mark bits.
> 
> For debugging applications, requiring that mark bits be on the side would be fine. But in general, we don't assume that mark bits are on the side because (we believe) it is more efficient (in time and space) to put the bits in the header in the cases where the VM is cooperative about it.

@steveblackburn We measured the performance, and option 2 performs better than option 1.  It is likely a result of less cache misses because according to `perf`, option 1 spent too much time setting VO bits when marking objects, while option 2 copies mark bits to VO bits in bulk sequentially after tracing.  However, we still made option 1 available in case the VM uses in-header mark bits.


> There are three use-cases (AFAIK):
> 
>     1. Stack-conservative GC, as we previously implemented in MMTk.   We took approach 1 because it was efficient and sufficient.
> 
>     2. Interior pointers.   We don't support them yet, but we want to.
> 
>     3. Debugging.
> 

We acknowledge that there will be multiple use cases, and some of them (including interior pointer and debugging) will require the VOB to be available during tracing.  We made it a Boolean flag in `ObjectSpace` to let the VM binding decide if it wants this capability.  But currently, the default strategy "CopyFromMarkBits" is both faster and able to make VOB available during tracing, so there is no additional cost for supporting this semantics.  But if the VM needs in-header mark bits and also wants VOB to be available during tracing, we currently don't have a strategy to support that.  The easiest workaround will be simply forcing the VM binding to use on-the-side mark bits, and reusing the header bit for other purposes, such as forwarding bits or pinning bits.
