### ISSUE TITLE
How to make an object pool?

### ISSUE THREAD

**Issue by oovm** [mmtk/mmtk-core#860]
I want to use a `Vec<u8>` as an object pool to store a series of objects that reference each other.

The simplified form is roughly as follows:

```rs
pub struct ObjectArena {
    buffer: Vec<u8>,
    roots: Gc<Value>,
}

pub enum Value {
    Null,
    Bool(bool),
    Number(f64),
    String(Gc<str>),
    List(Gc<Vec<Value>>),
    Map(Gc<HashMap<Value, Value>>),
}
```

I'm trying to use mmtk to do this, but I don't know how to start.

I have the following questions:

1. What traits do I need to implement on `ObjectArena`?
2. How should `GC` pointers be implemented? `GC<T>` needs to be able to dereference `&T`.
3. Can I make `Vec` and `HashMap` use `ObjectArena` as allocator, or do I need to reimplement `GcList` and `GcMap`?

**Comment by wks** [comment]
Why do you need to allocate objects in an "arena" instead of allocating each object individually?

If you want higher allocation speed, that's not necessary because allocation speed is very fast for bump-pointer allocators.  MMTk currently supports MarkCompact, SemiSpace, GenCopy and Immix variants which all use bump-pointer allocators.

From question 2 and 3, it looks like you are adding GC support for the Rust language, or making a runtime for another language and implementing it in Rust, like what Piccolo and gc-arena is doing.  Then you need to be aware that

-   When an allocation fails because the heap is full, GC will start.  For typical stop-the-world GC algorithms, the GC needs to make sure all mutators (application threads that can allocate objects or access objects in the GC heap) come to a stop before GC can start, because mutator activities (such as modifying a reference field while GC is running) can interfere with the correctness of GC
-   When GC starts, the GC needs to know the "root set" which usually consists of local variables, global variables or any VM-specific variables.  Objects pointed by those variables and all objects reachable from those objects will be kept alive by the GC, and other objects are dead and will be reclaimed.
-   Most GC algorithms using bump-pointer allocators need to move objects to counter heap fragmentation.  This means if an object is moved, all references pointing to that object must be updated to point to its new location.
-   Generational GC algorithms need to record every write access to reference fields (i.e. write barrier).  If a write operation modifies a mature object and makes it pointing to a young object, that old object (or its field) must be recorded, and that'll be part of the root set in minor GCs.

So the first question is how do you stop all mutators.  One easy answer is you only allow the heap to be accessed by one thread at a time.  If you need multiple mutator (application) threads to access the heap, I recommend implementing something like JNI where object allocations and accesses to object fields can only be done via API functions which are aware of GC.  Those API can block GC while they are running in progress, or be blocked by GC if GC is happening.

*(p.s. For managed languages such as Java, the VM implements "yield points" which are very efficient instructions that check if GC is requested and yield if it is.  Compilers of those VMs inject yield points in functions and loops.  Rust is not designed with GC in mind, so I don't think it is easy to let rustc insert "yieldpoints" for you.)*

The next question is how to find all `GC<T>` pointers in local variables, global variables, etc.  One way to implement it is making them "handles", i.e. *indirect* pointers using some kind of reference tables as intermediate.  For example, `GC<T>` contains a index into such a table, and such a table contains actual pointers to heap objects.  In this way,  GC only needs to scan the table for roots instead of finding all Rust variables that hold `GC<T>`.  This method is use by OpenJDK, Android ART, V8 and Lua (the official implementation from lua.org).  An alternative (used by SpiderMonkey) is making all `GC<T>` instances in local variables of a thread form a linked list, so that the GC can always follow the linked list to traverse all `GC<T>` in local variables on the stack.

If you use handles, that'll automatically solve the problem of object movement and write barriers.  Just implement them in the API.

Speaking of allocating Rust's `std::vec::Vec` and `std::collections::HashMap` in the GC'ed heap, I don't think that's possible because the Rust standard library is not aware that objects may move.  But I don't think it is difficult to implement your own `Vec<Value>` and `HashMap<Value, Value>`, either.
